baseURL       = "/"
languageCode  = "pt-br"
title         = "Projeto Múltiplos Olhares"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Início"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Sobre"
    url     = "sobre"
    weight  = 2
  [[menu.nav]]
    name    = "Artigos"
    url     = "artigos"
    weight  = 3
  [[menu.nav]]
    name    = "Vídeos"
    url     = "assistir"
    weight  = 4
  [[menu.nav]]
    name    = "Eventos"
    url     = "eventos"
    weight  = 5
  # [[menu.nav]]
  #   name    = "Blog"
  #   url     = "blog"
  #   weight  = 6
  [[menu.nav]]
    name    = "Contato"
    url     = "contato"
    weight  = 7

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Projeto Múltiplos Olhares"
  author = "Lucas Gouvêa"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Entre em Contato"
    url     = "contato"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/bgbrain2.png"
    heading               = "Projeto Múltiplos Olhares"
    tagline               = ""
    primary_button        = "Conheça"
    primary_button_url    = "sobre"
    secondary_button      = "Colabore"
    secondary_button_url  = "https://apoia.se/projetomultiplosriscos"

  [params.artigos]
    enable    = true
    title     = "ARTIGOS - ESCLEROSE E PANDEMIA"
    subtitle  = ""

  [params.assistir]
    enable    = true
    title     = "ASSISTA O DOCUMENTÁRIO"
    subtitle  = ""

  [params.eventos]
    enable    = true
    title     = "PARTICIPAÇÕES EM EVENTOS"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "APOIE O PROJETO"
    primary_button      = "Faça sua doação clicando aqui"
    primary_button_url  = "https://apoia.se/projetomultiplosriscos"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Patrocinador 1"
      address = ""
      phone   = ""
      email   = ""
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Patrocinador 2"
        [[params.footer.sitemap.link]]
          name = ""
          url  = ""
        [[params.footer.sitemap.link]]
          name = ""
          url  = "artigos"
        [[params.footer.sitemap.link]]
          name = ""
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = ""
          url  = "contato"
      # Footer Social Media
      [params.footer.social]
        title   = "Patrocinador 2"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Patrocinador 3"
        description = ""