baseURL       = "/"
languageCode  = "en-us"
title         = "Projeto Múltiplos Olhares"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Início"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Sobre"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Documentos"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contato"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Projeto Múltiplos Olhares"
  author = "Lucas Gouvêa"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/default-background.jpeg"
    heading               = "Projeto Múltiplos Olhares"
    tagline               = ""
    primary_button        = "Conheça o nosso Projeto"
    primary_button_url    = "portfolio"
    secondary_button      = "Colabore com o Projeto"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "DOCUMENTOS - DRA. ANA CANZONIEIRI"
    subtitle  = "Dra. Ana Canzonieiri é Psicologa e está auxiliando na confecção do projeto. É doutora em psicologia comportamental e elaborou pesquisas sobre a áreas da saude e a Covid durante o período da pandemia, além de um livro sobre a historia da Esclerose Múltipla."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "APOIE O PROJETO"
    primary_button      = "Faça sua doação clicando aqui"
    primary_button_url  = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"